/* ============ NEXUS VENDOR — seller portal ============ */
function PortalSidebar(kind, active, onNav) {
  const vendor = Session.vendor, admin = Session.user;
  const isVendor = kind === "vendor";
  const groups = isVendor ? [
    { title: t("workspace"), links: [["dashboard", I.grid, t("overview")], ["analytics", I.chart, t("analytics")], ["products", I.box, t("productsNav")], ["orders", I.cart, t("orders")]] },
    { title: t("finance"), links: [["payouts", I.wallet, t("payoutsNav")], ["coupons", I.tag, t("coupons")]] },
    { title: t("store"), links: [["store", I.store, t("store")], ["settings", I.cog, t("settings")]] },
  ] : [
    { title: t("adminSub"), links: [["dashboard", I.grid, t("overview")], ["analytics", I.chart, t("analytics")], ["vendors", I.store, t("sellers")], ["products", I.box, t("productsNav")], ["orders", I.cart, t("orders")]] },
    { title: t("finance"), links: [["users", I.users, t("users")], ["payouts", I.wallet, t("payoutsNav")], ["coupons", I.tag, t("coupons")]] },
    { title: t("settings"), links: [["settings", I.cog, t("settings")]] },
  ];
  const name = isVendor ? vendor?.name : admin?.name;
  return h("aside", { class: "sidebar", id: "portal-sidebar" },
    h("div", { style: { padding: "19px 18px", borderBottom: "1px solid var(--line)" } }, Logo(() => Router.go(isVendor ? "/vendor/dashboard" : "/admin/dashboard"), .86)),
    h("div", { style: { margin: "16px 15px", padding: "12px", borderRadius: "11px", background: "var(--panel)", border: "1px solid var(--line)", display: "flex", gap: "10px", alignItems: "center" } }, h("div", { style: { width: "34px", height: "34px", borderRadius: "10px", display: "grid", placeItems: "center", background: isVendor ? vendor?.banner : "linear-gradient(135deg,var(--pri),var(--acc))", fontSize: "17px" } }, isVendor ? vendor?.logo : admin?.avatar), h("div", { style: { overflow: "hidden" } }, h("div", { style: { fontSize: "12px", fontWeight: "700", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" } }, name), h("div", { style: { fontSize: "10px", color: "var(--mut)", marginTop: "2px" } }, isVendor ? t("sellerAccount") : t("administrator")))),
    h("div", { style: { padding: "0 10px", overflow: "auto", flex: 1 } }, groups.map((g) => h("div", { style: { marginBottom: "18px" } }, h("div", { style: { color: "var(--mut)", fontSize: "10px", textTransform: "uppercase", letterSpacing: ".12em", padding: "4px 10px 8px", fontWeight: "700" } }, g.title), g.links.map(([key, icon, label]) => h("button", { class: "nav-link " + (active === key ? "on" : ""), onclick: () => onNav(key) }, h("span", { class: "ico", style: { display: "flex" }, html: icon }), h("span", { style: { flex: 1, textAlign: "left" } }, label), key === "orders" && isVendor ? h("span", { class: "chip chip-bad", style: { padding: "2px 6px", fontSize: "10px" } }, Store.stats(vendor?.id).pending) : null))))),
    h("div", { style: { borderTop: "1px solid var(--line)", padding: "15px" } }, h("button", { class: "nav-link", onclick: () => { Session.logout(); Router.go("/"); App.render(); } }, h("span", { style: { display: "flex" }, html: I.logout }), t("signOut")), h("div", { style: { marginTop: "8px", display: "flex", justifyContent: "center" } }, ThemeToggle())));
}

function PortalTopbar(kind, active, title, subtitle) {
  const unread = Store.db.notifications.filter((n) => !n.read).length;
  return h("header", { style: { height: "70px", borderBottom: "1px solid var(--line)", display: "flex", alignItems: "center", gap: "16px", padding: "0 25px", background: "var(--bg2)", position: "sticky", top: 0, zIndex: 50 } },
    h("button", { class: "btn btn-g btn-sm mobile-menu", onclick: () => $("#portal-sidebar")?.classList.toggle("open") }, I.menu),
    h("div", { style: { flex: 1 } }, h("h1", { style: { margin: 0, fontSize: "19px" } }, title), h("div", { style: { color: "var(--mut)", fontSize: "12px", marginTop: "3px" } }, subtitle)),
    h("div", { style: { display: "flex", alignItems: "center", gap: "9px" } }, languageSwitcher(), NotifBell(unread), h("button", { class: "btn btn-g btn-sm", onclick: () => Router.go(kind === "vendor" ? "/vendor/" + Session.vendor.id : "/") }, kind === "vendor" ? t("viewStore") : t("viewMarketplace"), I.arrow)));
}

function PortalFrame(kind, active, title, subtitle, content) {
  return h("div", { style: { display: "flex", minHeight: "100vh", background: "var(--bg)" } }, PortalSidebar(kind, active, (key) => Router.go((kind === "vendor" ? "/vendor/" : "/admin/") + key)), h("div", { style: { flex: 1, minWidth: 0 } }, PortalTopbar(kind, active, title, subtitle), h("main", { style: { padding: "25px", maxWidth: "1700px", margin: "0 auto" } }, content)));
}

function TrendLabel(p) { return h("span", { class: "chip " + (p >= 0 ? "chip-ok" : "chip-bad"), style: { padding: "3px 8px" } }, p >= 0 ? "▲ " : "▼ ", Math.abs(p), "%"); }

function VendorOverview() {
  const v = Session.vendor, s = Store.stats(v.id), top = Store.topProducts(v.id, 5), cats = Store.categoryBreakdown(v.id);
  const head = h("div", { style: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "20px", flexWrap: "wrap", gap: "10px" } }, h("div", {}, h("h2", { style: { margin: 0, fontSize: "24px" } }, "Good morning, ", v.name.split(" ")[0], " 👋"), h("p", { style: { color: "var(--mut)", margin: "6px 0 0", fontSize: "13px" } }, "Here's what is happening with your store today.")), h("div", { style: { display: "flex", gap: "8px" } }, h("button", { class: "btn btn-g btn-sm", onclick: () => exportCSV(Store.ordersForVendor(v.id), "vendor-orders.csv") }, I.download, "Export"), h("button", { class: "btn btn-p btn-sm", onclick: () => Router.go("/vendor/products") }, I.plus, "Add product")));
  const stats = h("div", { style: { display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: "14px", marginBottom: "20px" } }, StatCard("Gross revenue", money(s.revenue), s.p30.growth, I.dollar, "vs previous 30d"), StatCard("Orders", num(s.orders), s.p30.orders - s.p30.prevOrders, I.cart, "last 30 days"), StatCard("Avg. order value", money(s.aov), s.p30.growth, I.trend, "per completed order"), StatCard("Store rating", v.rating + " / 5", null, I.star, num(v.reviews) + " reviews"));
  const revenueCard = h("div", { class: "card", style: { padding: "21px" } }, h("div", { style: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "12px" } }, h("div", {}, h("h3", { style: { margin: 0, fontSize: "16px" } }, "Revenue overview"), h("p", { style: { color: "var(--mut)", fontSize: "12px", margin: "5px 0 0" } }, "Last 30 days")), h("div", { style: { fontSize: "23px", fontWeight: "800" } }, money(s.p30.current))), AreaChart(s.revenueSeries, { height: 245 }));
  const categoryCard = h("div", { class: "card", style: { padding: "21px" } }, h("h3", { style: { margin: "0 0 17px", fontSize: "16px" } }, "Sales by category"), DonutChart(cats.map((x) => ({ label: x.name.split(" & ")[0], value: x.revenue }))));
  const topRows = top.map((x) => h("tr", {}, h("td", {}, h("div", { style: { display: "flex", gap: "9px", alignItems: "center" } }, h("span", { style: { fontSize: "25px" } }, x.emoji), h("span", {}, x.name))), h("td", {}, num(x.units)), h("td", {}, h("strong", {}, money(x.revenue)))));
  const topCard = h("div", { class: "card", style: { padding: "21px" } }, h("div", { style: { display: "flex", justifyContent: "space-between", marginBottom: "13px" } }, h("h3", { style: { margin: 0, fontSize: "16px" } }, "Top products"), h("button", { class: "btn btn-g btn-xs", onclick: () => Router.go("/vendor/products") }, "Manage all")), top.length ? h("table", { class: "tbl" }, h("thead", {}, h("tr", {}, ["Product", "Units", "Revenue"].map((x) => h("th", {}, x)))), h("tbody", {}, topRows)) : Empty("No sales yet", "Your top products will appear here."));
  const healthRows = [["Response rate", v.responseRate, "var(--acc)"], ["On-time shipping", v.shipOnTime, "var(--pri2)"], ["Product quality", Math.round(v.rating * 20), "var(--warn)"], ["Profile completeness", 88, "var(--pri2)"]].map(([label, n, color]) => h("div", { style: { marginBottom: "16px" } }, h("div", { style: { display: "flex", justifyContent: "space-between", fontSize: "12px", marginBottom: "7px" } }, h("span", {}, label), h("strong", {}, n + "%")), h("div", { style: { height: "7px", background: "var(--panel2)", borderRadius: "99px", overflow: "hidden" } }, h("div", { style: { width: n + "%", height: "100%", background: color, borderRadius: "inherit" } }))));
  const health = h("div", { class: "card", style: { padding: "21px" } }, h("h3", { style: { margin: "0 0 17px", fontSize: "16px" } }, "Store health"), healthRows);
  return h("div", { class: "fade-in" }, head, stats, h("div", { style: { display: "grid", gridTemplateColumns: "1.35fr .65fr", gap: "20px", marginBottom: "20px" } }, revenueCard, categoryCard), h("div", { style: { display: "grid", gridTemplateColumns: "1.3fr .7fr", gap: "20px" } }, topCard, health));
}

function ProductForm(existing, close) {
  const p = existing ? { ...existing, features: [...existing.features] } : { name: "", category: "electronics", price: "", compareAt: "", stock: "", emoji: "📦", description: "", features: ["", "", "", ""] };
  const field = (label, key, type = "text") => h("label", { style: { display: "grid", gap: "6px", fontSize: "12px", color: "var(--mut)" } }, label, h("input", { type, value: p[key], required: ["name", "price", "stock"].includes(key), oninput: (e) => p[key] = e.target.value }));
  const form = h("form", { style: { display: "grid", gap: "13px" }, onsubmit: (e) => { e.preventDefault(); const patch = { ...p, vendorId: Session.vendor.id, price: Number(p.price), compareAt: Number(p.compareAt || p.price), stock: Number(p.stock), features: p.features.filter(Boolean) }; Store.upsertProduct(patch); close(); toast(existing ? "Product updated" : "Product created", "ok"); } }, field("Product name", "name"), h("div", { style: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "10px" } }, h("label", { style: { display: "grid", gap: "6px", fontSize: "12px", color: "var(--mut)" } }, "Category", Select(p.category, CATEGORIES.map((c) => ({ value: c.id, label: c.name })), (v) => p.category = v, { width: "100%" })), field("Product emoji", "emoji")), h("div", { style: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "10px" } }, field("Selling price", "price", "number"), field("Compare-at price", "compareAt", "number")), field("Stock quantity", "stock", "number"), h("label", { style: { display: "grid", gap: "6px", fontSize: "12px", color: "var(--mut)" } }, "Description", h("textarea", { rows: 4, oninput: (e) => p.description = e.target.value }, p.description)), h("div", {}, h("div", { style: { fontSize: "12px", color: "var(--mut)", marginBottom: "7px" } }, "Key features"), h("div", { style: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px" } }, p.features.map((f, i) => h("input", { placeholder: "Feature " + (i + 1), value: f, oninput: (e) => p.features[i] = e.target.value })))), h("div", { style: { display: "flex", justifyContent: "flex-end", gap: "8px", marginTop: "5px" } }, h("button", { type: "button", class: "btn btn-g", onclick: close }, "Cancel"), h("button", { type: "submit", class: "btn btn-p" }, existing ? "Save changes" : "Create product")));
  return form;
}

function VendorProducts() {
  const v = Session.vendor; let q = "", status = "all";
  const wrap = h("div", {});
  const render = () => { let list = Store.products({ vendorId: v.id, q }); if (status !== "all") list = list.filter((p) => status === "low" ? p.stock > 0 && p.stock <= 25 : status === "out" ? p.stock === 0 : p.status === status); wrap.replaceChildren(h("div", { style: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "20px" } }, h("div", {}, h("h2", { style: { margin: 0, fontSize: "24px" } }, "Products"), h("p", { style: { color: "var(--mut)", margin: "5px 0 0", fontSize: "13px" } }, list.length + " products in your catalog")), h("button", { class: "btn btn-p", onclick: () => { const m = modal("Add product", ProductForm(null, () => m.close()), { width: "650px" }); } }, I.plus, "Add product")), Toolbar({ q, setQ: (x) => { q = x; render(); }, right: Select(status, [{ value: "all", label: "All status" }, { value: "active", label: "Active" }, { value: "low", label: "Low stock" }, { value: "out", label: "Out of stock" }], (x) => { status = x; render(); }) }), h("div", { class: "card", style: { overflow: "auto" } }, list.length ? h("table", { class: "tbl" }, h("thead", {}, h("tr", {}, ["Product", "SKU", "Price", "Stock", "Rating", "Status", "Actions"].map((x) => h("th", {}, x)))), h("tbody", {}, list.map((p) => h("tr", {}, h("td", {}, h("div", { style: { display: "flex", gap: "10px", alignItems: "center", minWidth: "240px" } }, h("span", { style: { width: "39px", height: "39px", borderRadius: "8px", background: "var(--panel2)", display: "grid", placeItems: "center", fontSize: "22px" } }, p.emoji), h("span", { style: { fontWeight: "600" } }, p.name))), h("td", { style: { color: "var(--mut)", fontFamily: "monospace", fontSize: "12px" } }, p.sku), h("td", {}, money(p.price)), h("td", { style: { color: p.stock <= 25 ? "var(--warn)" : "var(--txt)" } }, p.stock), h("td", {}, h("span", { class: "stars" }, stars(p.rating))), h("td", {}, StatusChip(p.stock === 0 ? "out_of_stock" : p.status)), h("td", {}, h("div", { style: { display: "flex", gap: "5px" } }, h("button", { class: "btn btn-g btn-xs", onclick: () => { const m = modal("Edit product", ProductForm(p, () => m.close()), { width: "650px" }); } }, I.edit), h("button", { class: "btn btn-d btn-xs", onclick: () => confirmDialog("Delete product?", "This action cannot be undone.", () => { Store.deleteProduct(p.id); toast("Product deleted", "ok"); render(); }, "Delete") }, I.trash))))))) : Empty("No products found", "Add your first product to start selling.", h("button", { class: "btn btn-p", onclick: () => { const m = modal("Add product", ProductForm(null, () => m.close()), { width: "650px" }); } }, "Add product")))); };
  render(); return wrap;
}

function OrdersTable(orders, vendorId, admin = false) {
  return h("div", { class: "card", style: { overflow: "auto" } }, orders.length ? h("table", { class: "tbl" }, h("thead", {}, h("tr", {}, ["Order", "Customer", "Date", "Items", "Total", "Status", "Action"].map((x) => h("th", {}, x)))), h("tbody", {}, orders.map((o) => h("tr", {}, h("td", {}, h("strong", {}, o.id)), h("td", {}, h("div", {}, o.customerName), h("div", { style: { color: "var(--mut)", fontSize: "11px" } }, o.customerEmail)), h("td", {}, dt(o.createdAt, "date")), h("td", {}, o.items.filter((i) => !vendorId || i.vendorId === vendorId).reduce((s, i) => s + i.qty, 0)), h("td", {}, money(vendorId ? o.items.filter((i) => i.vendorId === vendorId).reduce((s, i) => s + i.price * i.qty, 0) : o.total)), h("td", {}, StatusChip(o.status)), h("td", {}, h("button", { class: "btn btn-g btn-xs", onclick: () => OrderAdminModal(o, vendorId, admin) }, "Manage")))))) : Empty("No orders found", "New orders will show up here."));
}

function OrderAdminModal(o, vendorId, admin) {
  const next = ["pending", "processing", "shipped", "delivered", "cancelled", "refunded"].filter((s) => admin || s !== "refunded");
  const m = modal("Order " + o.id, h("div", {}, h("div", { style: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "13px", marginBottom: "18px" } }, h("div", { class: "card", style: { padding: "13px" } }, h("div", { style: { color: "var(--mut)", fontSize: "11px" } }, "CUSTOMER"), h("strong", {}, o.customerName), h("div", { style: { color: "var(--mut)", fontSize: "12px" } }, o.customerEmail)), h("div", { class: "card", style: { padding: "13px" } }, h("div", { style: { color: "var(--mut)", fontSize: "11px" } }, "TOTAL"), h("strong", { style: { fontSize: "20px" } }, money(o.total)), h("div", { style: { color: "var(--mut)", fontSize: "12px" } }, dt(o.createdAt)))), h("h4", { style: { margin: "0 0 10px" } }, "Items"), h("div", { style: { display: "grid", gap: "8px", marginBottom: "19px" } }, o.items.filter((i) => !vendorId || i.vendorId === vendorId).map((i) => h("div", { style: { display: "flex", gap: "8px", alignItems: "center", fontSize: "13px" } }, h("span", { style: { fontSize: "21px" } }, i.emoji), h("span", { style: { flex: 1 } }, i.name, " ×", i.qty), h("strong", {}, money(i.price * i.qty))))), h("h4", { style: { margin: "0 0 8px" } }, "Update status"), h("div", { style: { display: "flex", gap: "8px", flexWrap: "wrap" } }, next.map((s) => h("button", { class: "btn btn-sm " + (s === o.status ? "btn-p" : "btn-g"), onclick: () => { Store.updateOrder(o.id, { status: s }); toast("Order status updated", "ok"); m.close(); App.render(); } }, STATUS_META[s]?.label || s)))), { width: "610px" });
}

function VendorOrders() {
  const v = Session.vendor; let status = "all", q = "";
  const wrap = h("div", {}), render = () => { let list = Store.ordersForVendor(v.id); if (status !== "all") list = list.filter((o) => o.status === status); if (q) list = list.filter((o) => o.id.toLowerCase().includes(q.toLowerCase()) || o.customerName.toLowerCase().includes(q.toLowerCase())); wrap.replaceChildren(h("div", { style: { marginBottom: "20px" } }, h("h2", { style: { margin: 0, fontSize: "24px" } }, "Orders"), h("p", { style: { color: "var(--mut)", margin: "5px 0 0", fontSize: "13px" } }, "Manage and fulfill orders for your store.")), Toolbar({ q, setQ: (x) => { q = x; render(); }, right: Select(status, [{ value: "all", label: "All status" }, ...ORDER_STATUS.map((s) => ({ value: s, label: STATUS_META[s]?.label || s }))], (x) => { status = x; render(); }) }), OrdersTable(list, v.id)); }; render(); return wrap;
}

function VendorAnalytics() {
  const v = Session.vendor, s = Store.stats(v.id), series = Store.series(v.id, 12), top = Store.topProducts(v.id, 8);
  return h("div", { class: "fade-in" }, h("div", { style: { marginBottom: "22px" } }, h("h2", { style: { margin: 0, fontSize: "24px" } }, "Analytics"), h("p", { style: { color: "var(--mut)", margin: "5px 0 0", fontSize: "13px" } }, "Understand your store performance and customer behavior.")), h("div", { style: { display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: "14px", marginBottom: "20px" } }, StatCard("Revenue · 7 days", money(s.p7.current), s.p7.growth, I.dollar, "vs previous week"), StatCard("Orders · 7 days", num(s.p7.orders), s.p7.orders - s.p7.prevOrders, I.cart, "completed orders"), StatCard("Units sold", num(s.units), null, I.box, "all time"), StatCard("Conversion proxy", "8.4%", 1.8, I.trend, "store visits to order")), h("div", { style: { display: "grid", gridTemplateColumns: "1.4fr .6fr", gap: "20px", marginBottom: "20px" } }, h("div", { class: "card", style: { padding: "22px" } }, h("h3", { style: { margin: "0 0 16px", fontSize: "16px" } }, "Revenue trend"), AreaChart(series, { height: 270 })), h("div", { class: "card", style: { padding: "22px" } }, h("h3", { style: { margin: "0 0 17px", fontSize: "16px" } }, "Order status"), DonutChart([{ label: "Delivered", value: s.delivered, color: "#00d68f" }, { label: "Processing", value: s.processing, color: "#6d5efc" }, { label: "Shipped", value: s.shipped, color: "#4dabff" }, { label: "Pending", value: s.pending, color: "#ffb020" }, { label: "Other", value: s.cancelled + s.refunded, color: "#ff4d6a" }], { size: 180 }))), h("div", { class: "card", style: { padding: "22px" } }, h("h3", { style: { margin: "0 0 16px", fontSize: "16px" } }, "Product performance"), h("table", { class: "tbl" }, h("thead", {}, h("tr", {}, ["Product", "Units sold", "Revenue", "Share"].map((x) => h("th", {}, x)))), h("tbody", {}, top.map((p) => h("tr", {}, h("td", {}, p.emoji, " ", p.name), h("td", {}, num(p.units)), h("td", {}, money(p.revenue)), h("td", {}, h("span", { class: "chip chip-pri" }, Math.round(p.revenue / Math.max(s.revenue, 1) * 100) + "%"))))))));
}

function VendorPayouts() {
  const v = Session.vendor, ps = Store.db.payouts.filter((p) => p.vendorId === v.id);
  return h("div", { class: "fade-in" }, h("div", { style: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "20px" } }, h("div", {}, h("h2", { style: { margin: 0, fontSize: "24px" } }, "Payouts"), h("p", { style: { color: "var(--mut)", margin: "5px 0 0", fontSize: "13px" } }, "Track your earnings and payout history.")), h("button", { class: "btn btn-p", onclick: () => { if (v.balance < Store.db.settings.minPayout) return toast("Minimum payout is " + money(Store.db.settings.minPayout), "warn"); const p = { id: "PO-" + Math.floor(9000 + Math.random() * 9000), vendorId: v.id, amount: v.balance, status: "pending", requested: new Date().toISOString().slice(0, 10), paidAt: null, method: "Bank Transfer ••4471" }; Store.upsertPayout(p); v.pending += v.balance; v.balance = 0; Store.upsertVendor(v); toast("Payout requested", "ok"); App.render(); } }, I.wallet, "Request payout")), h("div", { style: { display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: "14px", marginBottom: "20px" } }, StatCard("Available balance", money(v.balance), null, I.wallet, "ready to withdraw"), StatCard("Pending balance", money(v.pending), null, I.clock, "being processed"), StatCard("Total paid out", money(ps.filter((p) => p.status === "paid").reduce((s, p) => s + p.amount, 0)), null, I.check, "lifetime")), h("div", { class: "card", style: { overflow: "auto" } }, ps.length ? h("table", { class: "tbl" }, h("thead", {}, h("tr", {}, ["Payout ID", "Requested", "Method", "Amount", "Status", "Paid"].map((x) => h("th", {}, x)))), h("tbody", {}, ps.map((p) => h("tr", {}, h("td", {}, h("strong", {}, p.id)), h("td", {}, p.requested), h("td", {}, p.method), h("td", {}, money(p.amount)), h("td", {}, StatusChip(p.status)), h("td", {}, p.paidAt || "—"))))) : Empty("No payouts yet", "Your payout history will appear here.")));
}

function VendorCoupons() {
  const list = Store.db.coupons;
  return h("div", { class: "fade-in" }, h("div", { style: { display: "flex", justifyContent: "space-between", marginBottom: "20px" } }, h("div", {}, h("h2", { style: { margin: 0, fontSize: "24px" } }, "Coupons"), h("p", { style: { color: "var(--mut)", margin: "5px 0 0", fontSize: "13px" } }, "Platform-wide promotion codes available to your customers.")), h("button", { class: "btn btn-p", onclick: () => toast("Coupon creation is managed by admins", "pri") }, I.plus, "Create coupon")), h("div", { class: "card", style: { overflow: "auto" } }, h("table", { class: "tbl" }, h("thead", {}, h("tr", {}, ["Code", "Offer", "Minimum", "Uses", "Expires", "Status"].map((x) => h("th", {}, x)))), h("tbody", {}, list.map((c) => h("tr", {}, h("td", {}, h("strong", {}, c.code)), h("td", {}, c.type === "percent" ? c.value + "% off" : c.type === "fixed" ? money(c.value) + " off" : "Free shipping"), h("td", {}, c.min ? money(c.min) : "No minimum"), h("td", {}, num(c.uses) + " / " + num(c.limit)), h("td", {}, c.expires), h("td", {}, StatusChip(c.active ? "active" : "cancelled"))))))));
}

function VendorSettings() {
  const v = Session.vendor, draft = { ...v };
  return h("div", { class: "fade-in" }, h("div", { style: { marginBottom: "20px" } }, h("h2", { style: { margin: 0, fontSize: "24px" } }, "Store settings"), h("p", { style: { color: "var(--mut)", margin: "5px 0 0", fontSize: "13px" } }, "Manage your storefront profile and business details.")), h("div", { style: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "20px" } }, h("div", { class: "card", style: { padding: "22px" } }, h("h3", { style: { marginTop: 0 } }, "Public profile"), h("div", { style: { display: "grid", gap: "14px" } }, h("label", {}, "Store name", h("input", { value: draft.name, oninput: (e) => draft.name = e.target.value })), h("label", {}, "Store description", h("textarea", { rows: 5, oninput: (e) => draft.description = e.target.value }, draft.description)), h("div", { style: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "10px" } }, h("label", {}, "Country", h("input", { value: draft.country, oninput: (e) => draft.country = e.target.value })), h("label", {}, "City", h("input", { value: draft.city, oninput: (e) => draft.city = e.target.value }))), h("button", { class: "btn btn-p", onclick: () => { Store.upsertVendor(draft); Session.vendor = { ...draft }; Session.persist(true); toast("Store settings saved", "ok"); } }, "Save changes"))), h("div", { class: "card", style: { padding: "22px" } }, h("h3", { style: { marginTop: 0 } }, "Store information"), [["Member since", dt(v.joined, "date")], ["Commission rate", v.commission + "%"], ["Seller plan", v.plan[0].toUpperCase() + v.plan.slice(1)], ["Store status", "Active"], ["Payout schedule", Store.db.settings.payoutSchedule]].map(([k, val]) => h("div", { style: { display: "flex", justifyContent: "space-between", padding: "13px 0", borderBottom: "1px solid var(--line)", fontSize: "13px" } }, h("span", { style: { color: "var(--mut)" } }, k), h("strong", {}, val))), h("div", { class: "card", style: { marginTop: "18px", padding: "15px", background: "rgba(255,176,32,.07)", borderColor: "rgba(255,176,32,.25)", fontSize: "12px", color: "var(--mut)", lineHeight: "1.6" } }, "Need help? Our seller support team responds within one business day. Contact support@nexus.dev"))));
}

function VendorPage(section = "dashboard") {
  if (!Session.vendor) { Router.go("/vendor/login"); return h("div"); }
  const map = { dashboard: [t("overview"), t("sellerSub"), VendorOverview], analytics: [t("analytics"), t("sellerSub"), VendorAnalytics], products: [t("productsNav"), t("sellerSub"), VendorProducts], orders: [t("orders"), t("sellerSub"), VendorOrders], payouts: [t("payoutsNav"), t("sellerSub"), VendorPayouts], coupons: [t("coupons"), t("sellerSub"), VendorCoupons], settings: [t("settings"), t("sellerSub"), VendorSettings], store: [t("store"), t("sellerSub"), () => VendorStorePage(Session.vendor.id)] };
  const [title, sub, fn] = map[section] || map.dashboard;
  return PortalFrame("vendor", section, title, sub, fn());
}
